# 禁用 swagger-ui try it out
springdoc:
  swagger-ui:
    supported-submit-methods:

# 数据源配置
mybatis-flex:
  datasource:
    master:
      driver-class-name: ${JDBC_DRIVER}
      url: ${JDBC_URL}
      username: ${JDBC_USERNAME}
      password: ${JDBC_PASSWORD}
      poolName: master

sa-token:
  # 是否输出操作日志
  is-log: false
  # 日志等级（trace、debug、info、warn、error、fatal）
  log-level: info

# 日志配置
logging:
  include-application-name: false
  level:
    root: info
    org.springframework.context.support.PostProcessorRegistrationDelegate: error
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    # springboot admin 日志颜色
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# 自定义配置
custom:
  jar-package:
    location: D:\tmp\upload-jar #jar包上传路径