server:
  port: 8080
  # 请求、响应编码问题
  servlet:
    encoding:
      force: true

spring:
  application:
    name: flink-etl-api
  # 环境
  profiles:
    active: dev

  # 事务配置
  transaction:
    default-timeout: 60s #事务超时时间
    rollback-on-commit-failure: true #提交失败回滚

  # 邮箱配置
  mail:
    #host: 没有配置host，自动配置类就不会加载，参考：org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
    port: ${MAIL_PORT:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    default-encoding: utf-8
    ssl:
      enabled: true
    properties:
      mail.debug: true
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000

  # jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    serialization:
      write-enums-using-to-string: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      read-enums-using-to-string: true
      read-unknown-enum-values-using-default-value: true

  # flyway: 数据库变更版本控制
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/base
      - classpath:db/migration/{vendor}
    baseline-on-migrate: true
    baseline-version: 0

  # springboot admin
  boot:
    admin:
      context-path: /admin #SBA 的 UI 和 API 统一前缀
      monitor:
        status-interval: 30s
      client:
        url: http://localhost:8080/admin

  output:
    ansi:
      enabled: always #日志颜色

  # 文件上传
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # Quartz配置，参考：SchedulerFactoryBean.initSchedulerFactory
  quartz:
    scheduler-name: ${spring.application.name} #集群名称
    job-store-type: jdbc #存储器类型，默认为 memory
    auto-startup: true #是否自动启动
    startup-delay: 0s #启动延迟
    wait-for-jobs-to-complete-on-shutdown: true #应用关闭时，是否等待定时任务执行完成，默认为 false
    overwrite-existing-jobs: true #是否覆盖已有Job的配置，仅适用于Bean注册
    properties: #quartz附加属性，参考：http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html
      org:
        quartz:
          # Scheduler配置
          scheduler:
            #instanceName: 不需要配置，同 spring.quartz.scheduler-name
            instanceId: AUTO #自动生成 instanceID
            instanceIdGenerator:
              class: org.quartz.simpl.SimpleInstanceIdGenerator #id生成策略类，默认为 SimpleInstanceIdGenerator
          # JobStore 相关配置
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #JobStore实现类
            #driverDelegateClass: 在 EnvironmentConfiguration 类中动态配置
            tablePrefix: QRTZ_ #Quartz表前缀
            isClustered: true #是集群模式
            clusterCheckinInterval: 15000 #集群检查频率，单位：毫秒。默认为 15000
            misfireThreshold: 60000 #调度器允许触发器超过其下次触发时间多少毫秒，超过该毫秒数则视为“未触发”，默认值60000
            useProperties: false
    jdbc:
      initialize-schema: never #不初始化数据库

  # 线程池配置
  task:
    execution:
      pool:
        core-size: 1
        max-size: 5
        queue-capacity: 50
        keep-alive: 60s
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 30s
      thread-name-prefix: quartz-

# 可观测性
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露监控端点
  httpexchanges:
    recording:
      include: TIME_TAKEN,REQUEST_HEADERS,RESPONSE_HEADERS,REMOTE_ADDRESS
  observations:
    annotations:
      enabled: true #开启注解支持
  # 参考：InfoContributorAutoConfiguration
  info:
    env:
      enabled: false
    git:
      enabled: true
      mode: simple
    build:
      enabled: true
    java:
      enabled: false
    os:
      enabled: true
    process:
      enabled: false
    ssl:
      enabled: false

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 前缀 例如:Bearer
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否打开自动续签 （如果此值为true，框架会在每次直接或间接调用 getLoginId() 时进行一次过期检查与续签操作）
  auto-renew: true
  # 是否从cookie读取token
  is-read-cookie: false
  # 是否从url参数读取token
  is-read-body: false

# spring doc
springdoc:
  show-actuator: true #actuator 端点添加到 swagger-ui
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha

# hikari配置
hikari-config: &hikari-config
  maxPoolSize: 5 #最大连接数
  minIdle: 1 #最小空闲连接数
  connectionTimeout: 5000 #获取连接超时，5秒
  validationTimeout: 5000 #校验连接时超时，5秒
  keepaliveTime: 120000 #保活时间，2分钟
  idleTimeout: 600000 #空闲时间，10分钟
  maxLifetime: 1200000 #最大存活时间，20分钟

# 多数据源，属性是通过反射设置的，参考：com.mybatisflex.core.datasource.DataSourceBuilder.setDataSourceProperties
mybatis-flex:
  datasource:
    master:
      <<: *hikari-config

# 日志配置
logging:
  include-application-name: false
  level:
    root: info
    org.springframework.context.support.PostProcessorRegistrationDelegate: error
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    # springboot admin 日志颜色
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

custom:
  default-pwd: 123456 #重置默认密码
  data-expiration:
    captcha: 3m #验证码数据过期时间
    http-exchange: 3d #http请求数据过期时间
    job-instance: 3d #任务实例数据过期时间
  send-mail:
    silent-time: 6h #邮件发送静默时间
