server:
  port: 8080
  # 请求、响应编码问题
  servlet:
    encoding:
      force: true

spring:
  application:
    name: flink-etl-api
  # 环境
  profiles:
    active: dev

  # 开发工具-热加载
  devtools:
    restart:
      additional-paths: src/main/java

  # 事务配置
  transaction:
    default-timeout: 60s #事务超时时间
    rollback-on-commit-failure: true #提交失败回滚

  # jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    serialization:
      write-enums-using-to-string: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      read-enums-using-to-string: true
      read-unknown-enum-values-using-default-value: true

  # flyway: 数据库变更版本控制
  flyway:
    enabled: true
    locations: classpath:db/mysql
    baseline-on-migrate: true
    baseline-version: 0

  # h2 控制台
  h2:
    console:
      path: /h2
      enabled: true

  #springboot admin
  boot:
    admin:
      client:
        url: http://localhost:8080
  output:
    ansi:
      enabled: always #日志颜色

# 可观测性
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露监控端点
  httpexchanges:
    recording:
      include: TIME_TAKEN,REQUEST_HEADERS,RESPONSE_HEADERS,REMOTE_ADDRESS
  observations:
    annotations:
      enabled: true #开启注解支持
  # 参考：InfoContributorAutoConfiguration
  info:
    env:
      enabled: false
    git:
      enabled: true
      mode: simple
    build:
      enabled: true
    java:
      enabled: false
    os:
      enabled: true
    process:
      enabled: false
    ssl:
      enabled: false

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 前缀 例如:Bearer
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否打开自动续签 （如果此值为true，框架会在每次直接或间接调用 getLoginId() 时进行一次过期检查与续签操作）
  auto-renew: true
  # 是否从cookie读取token
  is-read-cookie: false
  # 是否从url参数读取token
  is-read-body: false

# spring doc
springdoc:
  show-actuator: true #actuator 端点添加到 swagger-ui
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha

# hikari配置
hikari-config: &hikari-config
  maxPoolSize: 5 #最大连接数
  minIdle: 1 #最小空闲连接数
  connectionTimeout: 5000 #获取连接超时，5秒
  validationTimeout: 5000 #校验连接时超时，5秒
  keepaliveTime: 120000 #保活时间，2分钟
  idleTimeout: 600000 #空闲时间，10分钟
  maxLifetime: 1200000 #最大存活时间，20分钟

# 多数据源，属性是通过反射设置的，参考：com.mybatisflex.core.datasource.DataSourceBuilder.setDataSourceProperties
mybatis-flex:
  datasource:
    master:
      <<: *hikari-config

# 日志配置
logging:
  include-application-name: false
  level:
    root: info
    org.springframework.context.support.PostProcessorRegistrationDelegate: error
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    # springboot admin 日志颜色
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

custom:
  default-pwd: 123456 #重置默认密码
  captcha:
    expiration: 1m #验证码数据过期时间
  http-exchange:
    expiration: 1h #http请求数据过期时间